### ISSUE TITLE
Add v03 message format support.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarrac#18]
The (currently deployed) v02 message format uses AMQP headers, which are protocol dependent.  To move to a more protocol neutral transport, v03 puts the headers name:value pairs in the message payload itself.  The entire message is now a JSON tuple.  Need to add processing of v03 Json messages to maintain compatibility with the python implementation. JSON Format documented here:

https://github.com/MetPX/sarracenia/blob/master/doc/sr_postv3.7.rst

**Comment by petersilva** [comment]
I was going to wait until after WMO discussions had settled... v03 is just a first draft.  The actual content may change.

**Comment by petersilva** [comment]
Oh, and I left out a huge benefit.  This would remove the 255 character limit on string values.

**Comment by petersilva** [comment]
OK, I think what is in the man page now, is going to be good for many months.  It is produced by the python version 2.19.03b1... so it is probably safe to start work on it for C now also.

the json-c library is likely the one to use...  apt install libjson-c3 libjson-c-dev

**Comment by petersilva** [comment]
branch v03 implemented this, by here: d79c1f6b8da826317cc9aeea46a4890922e5e5d3

**Comment by petersilva** [comment]
not urgent, but for completeness... There is one major piece of v03 missing:  content embedding.
If you look at the protocol/message format specification:

https://github.com/MetPX/sarracenia/blob/master/doc/sr_postv3.7.rst

There is a *content* header. The content is for including the file data in the message, either
in raw utf-8, or encoded base64.  This is only intended to be used as an optimiization for use
with small files, so the use of a static buffer set to the maximum size of an embedded message
is reasonable.  

So the logic is basically:
   -- read the entire file into a static buffer.
   -- (as you are reading have a flag that identifies non utf-8 characters in the stream.)
   -- if there is non-utf8 in the stream, then:
   -- transfer to a encode in base64 to a second static buffer.

Can work on this on the v03 branch.

**Comment by msaraga** [comment]
Any recommendations as to what would be reasonable for the maximum embedded file size?

**Comment by petersilva** [comment]
so the current code has SR_SARRAC_MAXIMUM... is 1 MB... which is the size of the buffer. 500,000 bytes is the WMO limit for bulletins... good enough as an upper bound.  Since larger stuff is likely to be base64 encoded... which adds 50% bloat... 512 becomes 768 K bytes, leaves 256K for all the other fields... yeah,.. reasonable.

The actual amount will be tunable (prefer to use 4KB) but 500,000 bytes as upper bound is OK.

**Comment by petersilva** [comment]
the base64 encoding needs to omit line feeds. as discussed in  ( https://github.com/MetPX/sarracenia/issues/234 )

**Comment by petersilva** [comment]
need to fix base64 encoding not to inject line feeds, escaped or otherwise.

**Comment by petersilva** [comment]
need to update this to match: https://github.com/MetPX/sarracenia/issues/547

**Comment by petersilva** [comment]
this is long done.
