### ISSUE TITLE
Sarrac flow test independence from python implementation

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#21]
The current flow test is not optimal for long-term development of sarrac (slow testing). An independent flow test would be cool!

**Comment by petersilva** [comment]
fwiw, the C version only does a fraction of what the python one does, so such a self-test would be very boring.  C one doesn't download, for example, doesn't support plugins (which are useful for instrumenting test suites.) etc... and you risk losing perfect interoperabilty if they diverge.  The C and python are good together... It is likely more helpful than hurtful to have them together. but whatever, more testing can't be bad!
