### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#22]
Questions regarding tests for sarrac:

What is the purpose of each of the tests in this repo?
--> Adding comments/descriptions

What do we want to be testing for exactly?

**Comment by petersilva** [comment]
The C ones are unit tests to check corresponding files cachetest.c tests cache.c  etc...
the test*.sh scripts are used by packages for different installation methods.  For example packaging on the PPP is done by Daluma from the Optimization group.  they install using SSM, I guess test-ssm.sh comes from him. test_local.sh it to try local posts during development.... they use them as sanity checks to try posting and see that it doesn't dump core ;-)

What are you looking for?

**Comment by msaraga** [comment]
That about sums it up for now! Thanks
