### ISSUE TITLE
old arbitrary checksum and checksum caching feature discussion (split and closed)

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarrac#28]
work like python implementation, as per: https://github.com/MetPX/sarracenia/issues/54

When you calculate a file's checksum, store it in extended attributes named: **sr_mtime**, and **sr_sum**.   If those attributes are there, check if they can be used before you read the whole file again to re-calculate  the checksum from scratch.   make sure to overwrite the attribute when you need to.  fail gracefully if you can't set the attribute, because this is just an optimization and it may fail for reasons like permissions, or the file system not supporting it (in which case you just fall back to having to re-calculate it.)

**Comment by petersilva** [comment]
This is also required for DMS compatibility.

**Comment by msaraga** [comment]
what is DMS?

**Comment by petersilva** [comment]
internal ECCC project: Data Management Service... a huge java thing that applies 1000's of QA checks to data, and produces all manner of products... very XML oriented.

**Comment by msaraga** [comment]
sr_cpost logical sequence of events wrt to xattr/arbitrary checksum stuff:

./sr_cpost ...

...  config parsing ...

... xattr init sequence ...

can we set xattrs?
> yes : are xattrs set?
>> yes : is sr_sum valid?
>>> yes : do nothing
>>> no  : update xattrs

>> no  : set xattrs

> no  : are xattrs set?
>> yes : is sr_sum valid?
>>> yes : do nothing
>>> no  : ignore 

>> no  : no xattr or arbitrary checksum support

...

... xattr management on post ...

are xattrs set?
> yes : is sr_sum valid?
>> yes : post with sr_sum
>> no  : can we set xattrs?
>>> yes : update sr_sum, post with sr_sum
>>> no  : ignore

> no  : ignore, post with default behaviour

what do you guys think?

**Comment by msaraga** [comment]
there could be two configuration options for arbitrary checksum:
`-sum a`
<> get arbitrary checksum from xattrs only
`-sum a,whatevermyarbitrarychecksumisxD`
<> set arbitrary checksum to string after comma for all watched files (initialy), get arbitrary checksum from xattrs (after)

**Comment by msaraga** [comment]
do we want a config option to toggle xattr/arbitrary checksum support?
e.g.
`-xattr on|off`

**Comment by msaraga** [comment]
#44 
#45
