### ISSUE TITLE
disambiguate use cases for strip and post_base_dir options (& consolidate?)

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#29]
The strip and post_base_dir options are both currently being used to remove the beginning of file paths. It would be great to clarify which should be used for the future and to deprecate the other (while maintaining backward compatibility, of course..)

**Comment by petersilva** [comment]
* strip is for modifying relative paths.   

* post_base_dir is for establishing the base_directory (absolute path origin?) of a tree. 

They are fundamentally different, and can be used together or separately.  They shouldn´t conflict or even effect eachother, as they operate on different parts of paths.  I don´t see any potential for consolidation.

**Comment by msaraga** [comment]
thx for clarifying!
