### ISSUE TITLE
memory leak hunt

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#30]
Track down and resolve memory leaks! Valgrind is our friend...

**Comment by petersilva** [comment]
As far as we can tell from extensive work with valgrind, there are no leaks. period.

I agree this is a perennial worry, but think it is addressed by the inclusion of valgrind int the testing/release process.   Every time the code changes, this needs to be verified, as such problems can sneak in at any time. I added explicit reference to valgrind invocation in the README.rst as part of the pre-release quality work::

https://github.com/MetPX/sarrac/blob/master/README.rst#release-process

( commit : f710e23d05eabd171cbe462d1e1f1e54d481ba38 )

Is there anything else we can do?

**Comment by msaraga** [comment]
I'd like to come up with a more systematic way to check different pathways for memory leaks: #46 and unit test refactoring (fall 2019?) could be a good time to do this
