### ISSUE TITLE
sr_cpump missing half of the notifications received.

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#38]
local testing indicates that the cpump effectively reads from the source queue, but half of notifications are not logged (once every two incoming notifs)
it is currently unknown whether the notifications are properly transmitted: an experiment with sr_cpost -> sr_cpump -> sr_subscribe could determine this

**Comment by petersilva** [comment]
I confirmed this.  I just copied local_post.conf to local_sub.conf (and modified it.) and 
it posts every second message.   there is deep confusion in sr_consume routine, as there is a mix
of amqp_basic_consume, and then there are individual frame consumption calls... it should be one or the other.

**Comment by petersilva** [comment]
fix committed 49f2b2ceb5b5816ff92acb81b200e0ce1e7d6370
