### ISSUE TITLE
add checksum caching support

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#44]
source #28

**Comment by msaraga** [comment]
sr_cpost logical sequence of events wrt to xattr checksum caching:

./sr_cpost ...

...

... xattr management on sr_post call ...

> are xattrs set?
>> yes : is (sr_mtime >= mtime) ?
>>> yes : post with sr_sum
>>> no  : can we set xattrs?
>>>> yes : update sr_sum, post with sr_sum
>>>> no  : ignore, post with default behaviour

>> no  : can we set xattrs?
>>> yes : set sr_sum, post with sr_sum
>>> no  : ignore, post with default behaviour

@petersilva @habilinour

**Comment by msaraga** [comment]
What's the point of this feature?
* faster restarts
* avoid recomputing sum on `mv` type operations
* support for arbitrary checksum caching across processes #45 #28

**Comment by msaraga** [comment]
Do we want a configuration option to manage this feature?
e.g.
`-checksum_caching on|off...yes|no...true|false`

**Comment by petersilva** [comment]
I think checksum_caching is too confusing with the existing options: cache (which caches checksums to look for file duplicates.) in python there is something called xattr_disable  (default: off) which has an equally crappy name... a more appropriate name would be good.

but I can't think of one at the moment... anyway.. if you implement, then to be consistent with python, such an option it should be called xattr_disable for now... but a better name is certainly welcome.   also  xattr_disable False indicating that xattr feature is not disabled... well it's kind of circumlocuitous, ain't it... We we get a good idea, we'll change it in both.

**Comment by msaraga** [comment]
how's about `xattr_checksum_caching | xcc`?

**Comment by petersilva** [comment]
so on windows, the feature is implemented using alternative data streams, because NTFS doesn´t have xattr support.   so.... does xattr belong in the name...

**Comment by msaraga** [comment]
pretty hilarious... here are some more propositions:
```
metadata_checksum_caching
metadata_caching
metadata_optimization
metadata_checksum_optimization
checksum_optimization
```
