### ISSUE TITLE
c only binds to a single exchange.  with python you can bind to several.

### ISSUE THREAD

**Issue by michelgrenier** [MetPX/sarrac#51]
on the python side it is possible to have a sequence of options like this
exchange  xs_user1
subtopic    *.product_path_of_user1_files.#
exchange xs_user2
subtopic *.product_path_of_user2_files.#

for any subtopic option given the last exchange specified with the subtopic are put
together in a list
When it is time to bind the queue  with exchange and keys,   we use each of these entry in the list

This needs to be done on the C  side

**Comment by petersilva** [comment]
actual fix is c4be3bbce316309f1876ad489a083359abba072c
