### ISSUE TITLE
difference in credential parsing python vs. C

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarrac#55]
in python implementation:

amqps://dd.weather.gc.ca  --> automatically looks for 

amqps://anonymous@dd.weather.gc.ca in credentials.conf

or perhaps it just looks for the same hostname and uses the first credential it finds.

but C just complains, no broker/credential, and bombs.

So must include user name in C.

**Comment by petersilva** [comment]
@msaraga no rush, but when there is time... can take a look at this.

**Comment by msaraga** [comment]
Just confirmed that the second possibility is what's happening in sarracenia: sr_credentials.get returns the first entry with a matching hostname when user/pass are not provided.

**Comment by msaraga** [comment]
This will make a great first issue to try out a new unit test structure!

**Comment by petersilva** [comment]
sounds good... I guess referencing #46, and #64
