### ISSUE TITLE
creating a new directory and file is ignored by sr_cpost.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarrac#59]
While the priming run walks a large tree, and inotify will now notice events everywhere in the tree, unfortunately if any new directories are made, any files in them will be ignored.
(offshoot discovered investigating #35, #57)

**Comment by petersilva** [comment]
to reproduce, in one terminal startup sr_cpost on a directory with -sleep 3 
in a separate terminal:

```
mkdir watched_directory
mkdir watched_directory/old_dir
sr_cpost -sleep 3 -p watched_directory -c something_that_posts.conf

cd watched_directory
mkdir new_dir
echo hoho  >new_dir/hoho
echo aha >thisworks
echo okinoldrialso >old_dir/oldok
```

hoho should be posted, but isn't.... thisworks and old_dir/oldok both get posted.

**Comment by petersilva** [comment]
I think this is fixed.

**Comment by msaraga** [comment]
Could not observe the reported behaviour locally as of https://github.com/MetPX/sarrac/commit/079cd3c2dad586f8b92b2e47d4e0868d83b7af28

**Comment by petersilva** [comment]
it takes seconds to reproduce the issue on that release for me...

**Comment by petersilva** [comment]
look at local_post.conf in the repo.

**Comment by msaraga** [comment]
Managed to reproduce the above noted behaviour using local_post.conf ...

I was using this simpler config, which produces the correct behaviours.
```
post_broker amqp://bunnymaster@localhost/
post_exchange xtest

#path /home/username/cpost_test/dd

#sleep 1

post_base_url file:/

events create,delete,link,modify

accept .*
```
Command:
```
sr_cpost -sleep 3 -p dd -c my_post.conf
```

**Comment by petersilva** [comment]
explanation was that the bug only arose if the *create* event is not selected (which catches directory creation events.)
