### ISSUE TITLE
cpump log error on null partstr

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarrac#60]
I guess this is related to what I discovered in sarracenia pull request 221 which is related to changes from issue212:

```
 2    sr_cpump_xvan_f14           (2 file)  [ERROR] no partstr, corrupt line 148 in cache file /local/ben/.cache/sarra/cpump/xvan
```

**Comment by msaraga** [comment]
TODO implement support for receiving messages missing partstr in sr_cpump

**Comment by petersilva** [comment]
partstr is now optional. and partitioned file support is removed from sr3. so this is moot.
