### ISSUE TITLE
unit testing: which framework should we use?

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#64]
So far, https://github.com/libcheck/check appears promising

**Comment by petersilva** [comment]
not contradicting... I imagine you looked at it... I googled c unit testing, and the first hit was cunit...
did an apt search cunit, and it´s there i bionic... so another candidate perhaps...
second hit was:

https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#C

In that list, check has more *yes* boxes than cunit...

api-sanity-checker looks interesting as an additional tool (not a replacement for check.)
can do some fuzzing with that... perhaps useful later.

**Comment by msaraga** [comment]
another fuzzer, looks fun
https://en.wikipedia.org/wiki/American_fuzzy_lop_(fuzzer)
