### ISSUE TITLE
 declare env not using subarg

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarrac#7]
in C option parsing for this line would not work because subarg is not call to resolve ${HOME}
declare env TESTDOCROOT=${HOME}/sarra_devdocroot

was: https://sourceforge.net/p/metpx/bugs/98/

**Comment by petersilva** [comment]
Hey Michael, you were playing with stuff with the other one, this one should be easy to take care of also.

**Comment by msaraga** [comment]
Curious test results so far: running flow test with debug logs for sarrac shows a number of correct substitutions of ${HOME} when used in default.conf on the line
```
declare env TESTDOCROOT=${HOME}/sarra_devdocroot
```
Behaviour described above is as expected given the current definition of `char *subarg` from `sr_config.c`. So `subarg` is being called at some point on the `default.conf` options; where isn't it being called?

--> Flow test fails for sarrac.
