### ISSUE TITLE
SUSE & RH RPM packaging

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#73]
Support for openSUSE 15

**Comment by msaraga** [comment]
librabbitmq is available as a pkg on opensuse: https://software.opensuse.org/package/librabbitmq-dev

**Comment by msaraga** [comment]
this could be really cool and easy if it works: https://wiki.debian.org/Alien

**Comment by msaraga** [comment]
@petersilva Would it be better to have a single pkg with libsarra, libsrshim, sr_cpost, sr_cpump, or the same pkg/dependency structure as with deb?

**Comment by petersilva** [comment]
that's good news!
need the header files for json and ssl as well, possible names of packages...  libopenssl-devel, libssl-devel, libjson-devel, libjson-c-devel...

**Comment by msaraga** [comment]
can confirm that the names are `libopenssl-devel`, `libjson-c-devel`

**Comment by petersilva** [comment]
in terms of packaging, you can stick it all in one package if you like.  For debian, we have separate packages:   sarrac  (contains sr_cpost, sr_cpump, and libsrshim.so)
libsarra package contains only libsarra.so., and then libsarrac-dev contains the .h file.

**Comment by msaraga** [comment]
For later reference, can now confirm that the `librabbitmq4` and `librabbitmq-devel` openSUSE15 packages available in the experimental OBS repo properly install on SLE15.

**Comment by petersilva** [comment]
can you provide the relevant zypper snippets (presumably another add repo... and then install) that would install them.

**Comment by msaraga** [comment]
```bash
For SLE 15 run the following as root:

zypper addrepo https://download.opensuse.org/repositories/network:messaging:amqp/SLE_15/network:messaging:amqp.repo
zypper refresh
zypper install librabbitmq4 librabbitmq-devel
```

For systems not connected to the internet, the rpm's are available at:
https://build.opensuse.org/package/show/network%3Amessaging%3Aamqp/librabbitmq4
