### ISSUE TITLE
sr_cpost does not watch trees originally created with wrong permissions.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarrac#83]
( copy of https://github.com/MetPX/sarracenia/issues/289 )

**Comment by petersilva** [comment]
6a3f98db420b183794a70e587f3e4149a36c98e7 

7a4b989a5cabec9317bb2e1bcdce6b7c4a683208

fixed.

**Comment by petersilva** [comment]
@habilinour is this fixed / can we close the issue?

**Comment by habilinour** [comment]
The issue is fixed.
